// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTIaxN9hhm_brdzhIUdk4EtqsfIIu0kmY',
    appId: '1:527536496956:android:679657816b3c44fc44fe39',
    messagingSenderId: '527536496956',
    projectId: 'lab09-8d752',
    storageBucket: 'lab09-8d752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrQHe0WEKWYn043nPWyjwcS5fs3J9w9h8',
    appId: '1:527536496956:ios:794e374eb20d117744fe39',
    messagingSenderId: '527536496956',
    projectId: 'lab09-8d752',
    storageBucket: 'lab09-8d752.appspot.com',
    iosClientId: '527536496956-bsp4nlps4q5rsf6pic2nov6jjt9lacq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrQHe0WEKWYn043nPWyjwcS5fs3J9w9h8',
    appId: '1:527536496956:ios:794e374eb20d117744fe39',
    messagingSenderId: '527536496956',
    projectId: 'lab09-8d752',
    storageBucket: 'lab09-8d752.appspot.com',
    iosClientId: '527536496956-bsp4nlps4q5rsf6pic2nov6jjt9lacq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab09',
  );
}
